import * as change_case from "change-case";
import * as pluralize from "pluralize";
import { ISetting } from "./isetting";
import { IDatabaseColumn, IDatabaseTable } from "./mysql-database-definition";

export default class InterfaceBuilder {
  constructor(private settings: ISetting, private mysqlTypes: { [key: string]: string }) {

  }

  public renderTs(tableName: string, table: IDatabaseTable): string {
    const className = this.getClassName(tableName);
    let stringBuilder = this.settings.defaultClassModifier + " " + className + " { \n";
    for (const colName in table) {
      stringBuilder += this.buildTypeRow(table[colName]);
    }
    stringBuilder += "}";
    const meta = `/**\n* Autogenerated interface, DO NOT MODIFY\n*/\n`;
    return meta + stringBuilder;
  }

  private buildTypeRow(col: IDatabaseColumn): string {
    const tabs = "\t";
    const optional = this.settings.optionalParameters ? "?" : "";
    const tsType = this.getTsType(col.type);
    const field = col.field;
    return `${tabs}"${field}"${optional}: ${tsType};\n`;
  }

  private getTsType(type: string): string {
    let ts = this.mysqlTypes[type];
    if (!ts) {
      // tslint:disable-next-line:no-console
      console.error("Unknown type " + type);
      ts = "any";
    }
    return ts;
  }

  private getClassName(tableName: string): string {
    const name = this.settings.singularizeClassNames ? pluralize.singular(tableName) : tableName;
    const preI = this.settings.appendIToDeclaration ? "I" : "";
    return preI + change_case.pascalCase(name);
  }
}
